apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "message-queue.fullname" . }}-config
  labels:
    {{- include "message-queue.labels" . | nindent 4 }}
data:
  MQ_PARTITION_COUNT: "{{ .Values.config.partitionCount }}"
  MQ_RETENTION_HOURS: "{{ .Values.config.retentionHours }}"
  MQ_HEARTBEAT_TIMEOUT_SEC: "{{ .Values.config.heartbeatTimeoutSec }}"
  MQ_MAX_PARTITION_SIZE: "{{ .Values.config.maxPartitionSize }}"
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
